export const AJAX_BEGIN = 'AJAX_BEGIN'
export const AJAX_ERROR = 'AJAX_ERROR'

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const REDIRECTED = 'REDIRECTED'

export const GET_YEARLY_BALANCE_SUCCESS = 'GET_YEARLY_BALANCE_SUCCESS'
export const GET_MONTLY_BALANCE_SUCCESS = 'GET_MONTLY_BALANCE_SUCCESS'
export const SAVE_MONTLY_INCOME_BUDGET = 'SAVE_MONTLY_INCOME_BUDGET'
export const ADD_EXPENSE_SUCCESS = 'ADD_EXPENSE_SUCCESS'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'